---
# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # secret files using GCP KMS to encrypt the stored PGP keys
  - path_regex: kubernetes/.*/*.enc.ya?ml
    encrypted_regex: ^(data|stringData)$
    unencrypted-regex: ^(description|metadata)$
    gcp_kms: projects/atomic-gke-clusters/locations/global/keyRings/sops/cryptoKeys/sops-key
