apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

patches:
  # REQUIRED: Adds SOPs integration to GCP KMS via WLI
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        namespace: flux-system
        annotations:
          iam.gke.io/gcp-service-account: sops-sa@atomic-gke-clusters.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: kustomize-controller
      namespace: flux-system
  # REQUIRED: Due to the kustomize controllers needing the ability to decrypt in the cluster without needing to add explicitly.
  # TODO: This should be removed once this repository reaches a stable point where all secrets are defined in the repository.
  - patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        decryption:
          provider: sops
    target:
      kind: Kustomization
      name: flux-system
      namespace: flux-system
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    path: ../../patches/deployment.yaml
