---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-namespaces
  namespace: flux-system
spec:
  interval: 10m
  timeout: 30m
  path: kubernetes/namespaces/overlays/cluster-03
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
