---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 30s
  prune: true
  wait: false
  force: false
  path: ./kubernetes/tenants/overlays/cluster-03
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: platform-namespaces
      namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
