---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-01
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: ${GCP_PROJECT_ID}
spec:
  enableAutopilot: true
  location: australia-southeast1
  releaseChannel:
    channel: RAPID
  workloadIdentityConfig:
    workloadPool: ${GCP_PROJECT_ID}.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster-01
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: ${GCP_PROJECT_ID}
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/australia-southeast1/clusters/cluster-01
  endpoint:
    gkeCluster:
      resourceRef:
        name: cluster-01
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: cluster-01
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: ${GCP_PROJECT_ID}
spec:
  location: global
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-01
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cluster-01
  namespace: flux-system
spec:
  summary: "cluster-01"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "cluster-01"
      namespace: flux-system
  providerRef:
    name: flux-system-dispatch
  eventMetadata:
    project: "${GCP_PROJECT_ID}"
    cluster: "cluster-01"
    location: "australia-southeast1"
  inclusionList:
    - ".*check passed.*"
